Big alias.bash revamp

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -8,47 +8,123 @@ case $- in
       *) return;;
 esac
 
-################################################################################
+#----------------------------------------------------------------------------------------------------
+# colors
+#----------------------------------------------------------------------------------------------------
+DARKGRAY='\e[1;30m'
+LIGHTRED='\e[1;31m'
+GREEN='\e[32m'
+YELLOW='\e[1;33m'
+LIGHTBLUE='\e[1;34m'
+NC='\e[m'
+
+#----------------------------------------------------------------------------------------------------
 # Path
-################################################################################
-# don't put duplicate lines or lines starting with space in the history.
-# See bash(1) for more options
-HISTCONTROL=ignoreboth
-
-# append to the history file, don't overwrite it
-shopt -s histappend
-
-# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
-HISTSIZE=1000
-HISTFILESIZE=2000
-# Change the format of the history output: does not print date, instead 
-# print carriage return "\r" and clear line (ANSI K code)
-# HISTTIMEFORMAT=$'\r\e[K'
-# Also we could use this alias ...
-# HISTTIMEFORMAT=$'\r\e[K' history
-
-################################################################################
-# Path
-################################################################################
+#----------------------------------------------------------------------------------------------------
 export PATH=$HOME/.local/bin:$PATH
+export PATH=${HOME}/bin:$PATH
 # export PATH=$HOME/bin:$PATH
 
-################################################################################
-# Custom
-################################################################################
+# export PATH=${HOME}/.local/texlive/2022/bin/x86_64-linux:$PATH
+# export PATH="$PATH:$HOME/esp/xtensa-lx106-elf/bin"
+# export IDF_PATH="$HOME/esp/ESP8266_RTOS_SDK"
+
+#----------------------------------------------------------------------------------------------------
+# sh options: `shopt -p` lists all already set
+#----------------------------------------------------------------------------------------------------
 set bell-style none             #no bell
 shopt -s autocd                 #cd dir with name
-################################################################################
+# CTRL-s hangs the emulator, disable
+stty -ixon
 
 # check the window size after each command and, if necessary,
 # update the values of LINES and COLUMNS.  shopt -s checkwinsize # If set, the pattern "**" used in a pathname expansion context will
 # match all files and zero or more directories and subdirectories.
 shopt -s globstar
 
-################################################################################
-# bindings: this stuff is better done in profile (w/o bind word there)
-################################################################################
-#bind -m vi # this is stuff is done in profile
+#----------------------------------------------------------------------------------------------------
+# Env variables: TODO: these should go to bash_profile?
+#----------------------------------------------------------------------------------------------------
+# Other gloval variables
+export EDITOR=/usr/bin/vim
+# colored GCC warnings and errors
+export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
+
+export MANPATH=${HOME}/.local/texlive/2022/texmf-dist/doc/man:$MANPATH
+
+# Use "bat" for man pages
+export MANPAGER="sh -c 'col -bx | bat -l man -p'"
+# This is needed to properly show colors
+export MANROFFOPT="-c"
+
+# Modify default options for fzf
+export FZF_DEFAULT_OPTS='--height 50% --border'
+
+# CTRL-T - Paste the selected files and directories onto the command line
+# Set FZF_CTRL_T_COMMAND to override the default command
+# Set FZF_CTRL_T_OPTS to pass additional options
+
+# CTRL-R - Paste the selected command from history onto the command line
+# If you want to see the commands in chronological order, press CTRL-R again which toggles sorting by relevance
+# Set FZF_CTRL_R_OPTS to pass additional options
+
+# ALT-C - cd into the selected directory
+# Set FZF_ALT_C_COMMAND to override the default command
+# Set FZF_ALT_C_OPTS to pass additional options
+
+#----------------------------------------------------------------------------------------------------
+# History
+#----------------------------------------------------------------------------------------------------
+
+# HISTFILE=$HOME/.bhistfile
+HISTSIZE=10000
+HISTFILESIZE=20000
+
+# don't put duplicate lines or lines starting with space in the history.
+HISTCONTROL=ignoreboth
+
+export TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'
+export HISTIGNORE="&:bg:fg:ll:h"
+# export HISTTIMEFORMAT="$(echo -e ${GREEN})[%d/%m %H:%M:%S]$(echo -e ${NC}) "
+export HISTTIMEFORMAT="$(echo -e ${GREEN})[%d/%m %H:%M]$(echo -e ${NC}) "
+
+# append to the history file, don't overwrite it
+shopt -s histappend
+
+# Change the format of the history output: does not print date, instead 
+# print carriage return "\r" and clear line (ANSI K code)
+# HISTTIMEFORMAT=$'\r\e[K'
+# Also we could use this alias ...
+# HISTTIMEFORMAT=$'\r\e[K' history
+
+#----------------------------------------------------------------------------------------------------
+# Custom less
+#----------------------------------------------------------------------------------------------------
+# make less more friendly for non-text input files, see lesspipe(1)
+[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
+
+# See below for explanation
+export LESS="-SXIFRs"
+
+# -S: do not wrap lines, side scroll with left/right arrow keys
+# -X: leave contents on screen when less exits
+# -I: ignore case when searching with / or ?
+# -F: quit immediately when the entire file fits in one screen
+# -R: enable colored output
+# -s: squeeze blank lines into a single blank line
+# Coloured LESS
+# export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode – red
+# export LESS_TERMCAP_md=$(printf '\e[01;32m') # enter double-bright mode – (was 32, green)
+# export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
+# export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
+# export LESS_TERMCAP_so=$(printf '\e[01;41m') # enter standout mode – red (was 33, yellow)
+# export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
+# export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode – cyan
+
+#----------------------------------------------------------------------------------------------------
+# Custom bindings (general ones done in profile)
+# TODO: working, play with this !
+#----------------------------------------------------------------------------------------------------
 # Custom bindings to commands ! Eg Ctrl-Y run "ls"
 # bind -x '"\C-y":"ls"'
 # If it is not working, try deleting the binding first. Eg Ctrl-o does
@@ -56,78 +132,37 @@ shopt -s globstar
 # bind -r "\C-o"
 # bind -x '"\C-o":"ev"'
 
-# make less more friendly for non-text input files, see lesspipe(1)
-[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
+# # Map a keystroke to a template, useful when learning
+# # a language and need to create quick templates. Make this 
+# # function take args and so make it for several languages
+# create-template (){
+# cat << EOF > template.sh
+# Hello
+# World
+# !
+# EOF
+# echo "template.sh created"
+# }
+# # Work with both ...
+# bind -x '"\C-e":"create-template"'
 
-# set variable identifying the chroot you work in (used in the prompt below)
-if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-    debian_chroot=$(cat /etc/debian_chroot)
-fi
+#----------------------------------------------------------------------------------------------------
+# Use bash-completion, if available
+#----------------------------------------------------------------------------------------------------
+[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
+source /usr/share/bash-completion/bash_completion
 
-# set a fancy prompt (non-color, unless we know we "want" color)
-case "$TERM" in
-    xterm-color|*-256color) color_prompt=yes;;
-esac
-
-# uncomment for a colored prompt, if the terminal has the capability; turned
-# off by default to not distract the user: the focus in a terminal window
-# should be on the output of commands, not on the prompt
-#force_color_prompt=yes
-
-if [ -n "$force_color_prompt" ]; then
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-	# We have color support; assume it's compliant with Ecma-48
-	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
-	# a case would tend to support setf rather than setaf.)
-	color_prompt=yes
-    else
-	color_prompt=
-    fi
-fi
-
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-else
-    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-fi
-unset color_prompt force_color_prompt
-
-# If this is an xterm set the title to user@host:dir
-case "$TERM" in
-xterm*|rxvt*)
-    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    ;;
-*)
-    ;;
-esac
-
-# enable color support of ls and also add handy aliases
-if [ -x /usr/bin/dircolors ]; then
-    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
-    alias ls='ls --color=auto'
-    #alias dir='dir --color=auto'
-    #alias vdir='vdir --color=auto'
-
-    #alias grep='grep --color=auto'
-    #alias fgrep='fgrep --color=auto'
-    #alias egrep='egrep --color=auto'
-fi
-
-# colored GCC warnings and errors
-export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
-
+#----------------------------------------------------------------------------------------------------
+# Load alias
+#----------------------------------------------------------------------------------------------------
 # Alias definitions.
-# You may want to put all your additions into a separate file like
-# ~/.bash_aliases, instead of adding them here directly.
-# See /usr/share/doc/bash-doc/examples in the bash-doc package.
-
 if [ -f ~/.alias ]; then
-    . ~/.alias
+  source ~/.alias
 fi
 
-# enable programmable completion features (you don't need to enable
-# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
-# sources /etc/bash.bashrc).
+#----------------------------------------------------------------------------------------------------
+# programmable completion features
+#----------------------------------------------------------------------------------------------------
 if ! shopt -oq posix; then
   if [ -f /usr/share/bash-completion/bash_completion ]; then
     . /usr/share/bash-completion/bash_completion
@@ -136,10 +171,74 @@ if ! shopt -oq posix; then
   fi
 fi
 
+#----------------------------------------------------------------------------------------------------
+# Prompt: Using tool-solution prompt. See below
+#----------------------------------------------------------------------------------------------------
+# # If this is an xterm set the title to user@host:dir
+# case "$TERM" in
+# xterm*|rxvt*)
+#     PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
+#     ;;
+# *)
+#     ;;
+# esac
 
-################################################################################
+#----------------------------------------------------------------------------------------------------
+# Liquidprompt
+#----------------------------------------------------------------------------------------------------
+
+# Only load Liquidprompt in interactive shells, not from a script or from scp
+[[ $- = *i* ]] && source ~/.liquidprompt/liquidprompt
+
+# If slow: `LP_DEBUG_TIME=1 ; lp_activate` to enable printing the runtime before
+# every prompt. This lets you see specific runtimes, and will let you observe
+# what changes improve the time.
+
+# Next, `declare -p | grep " LP_ENABLE"` which will print every config option
+# Keep disabling features until you find what makes a large change to your runtime
+# eg `LP_ENABLE_TEMP=0` -> This one did the trick!
+
+# # add time, jobs, load and battery
+# LP_PS1="${LP_PS1_PREFIX}${LP_TIME}${LP_BATT}${LP_LOAD}${LP_TEMP}${LP_JOBS}"
+# # add user, host and permissions colon
+# LP_PS1+="${LP_BRACKET_OPEN}${LP_USER}${LP_HOST}${LP_PERM}"
+# LP_PS1+="${LP_PWD}${LP_BRACKET_CLOSE}${LP_SCLS}${LP_VENV}${LP_RUBY_VENV}${LP_TFSPACE}${LP_PROXY}"
+# # Add VCS infos
+# LP_PS1+="${LP_VCS}"
+# # add return code and prompt mark
+# LP_PS1+="${LP_RUNTIME}${LP_ERR}${LP_MARK_PREFIX}${LP_COLOR_MARK}${LP_MARK}${LP_PS1_POSTFIX}"
+# # Get the current prompt on the fly and make it a title
+# _lp_formatted_title "$LP_PS1"
+
+##----------------------------------------------------------------------------------------------------
+## Powerline: SIMPLE and compatible with csh !
+## pip install powerline-shell
+##----------------------------------------------------------------------------------------------------
+#function _update_ps1() {
+#    PS1=$(powerline-shell $?)
+#}
+#if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
+#    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
+#fi
+
+##----------------------------------------------------------------------------------------------------
+## Powerline : TOO FREAKING COMPLEX in SETTING UP. BIG FUCK YOU
+## Install it via system : apt get powerline
+## Install it with: pip install powerline-status
+## In Fedora: Copy files from /etc/xdg/powerline into ~/.config/powerline
+##----------------------------------------------------------------------------------------------------
+## Run powerline-daemon --replace to reload configuration
+#if [ -f $(which powerline-daemon) ]; then
+#  powerline-daemon -q
+#  POWERLINE_BASH_CONTINUATION=1
+#  POWERLINE_BASH_SELECT=1
+#  source /usr/share/powerline/bash/powerline.sh
+#fi
+
+
+#----------------------------------------------------------------------------------------------------
 # FZF
-################################################################################
+#----------------------------------------------------------------------------------------------------
 [ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash
 
 # When selecting files with fzf, we show file content with syntax highlighting,
